version: "3.8"

services:
   nginx: 
      image: nginx:latest
      container_name: nginx
      build:
         context: ./requirements/nginx
         dockerfile: Dockerfile
      ports:
         - "${NGINX_PORT}:80"
      volumes:
         - ./requirements/nginx/conf:/etc/nginx/conf.d:ro
      networks:
         - inception
      restart: always
      environment:
         - NGINX_HOST=${NGINX_HOST}
      env_file: ./.env
      # depends_on:
      #    mariadb:
      #       condition: service_completed_sucessfully
      #       restart: true


   # mariadb:
      # name: mariadb
   # wordpress:

   # bonus:
      # profiles: [bonus]     #used to launch only if specified with docker compose --profile bonus up


networks:
   inception:
      driver: bridge