version: "3.8"

services:
   nginx: 
      container_name: nginx
      build:
         context: ./requirements/nginx/
      ports:
         - "${NGINX_PORT}:80"
      volumes:
         - ./src/requirements/nginx/conf:/etc/nginx/conf.d:ro
      networks:
         - inception
      restart: always
      env_file: ./.env
      depends_on:
         - wordpress

      # depends_on:
      #    mariadb:
      #       condition: service_completed_sucessfully
      #       restart: true

   wordpress:
      image: wordpress:latest
      container_name: wordpress
      volumes:
         - ./requirements/wordpress:/var/www/html
      # depends_on:
      #    - mariadb

   mariadb:
      container_name: mariadb
      image: mariadb:latest
      volumes:
         - ./requirements/mariadb:/etc/mysql/conf.d:ro

      env_file:
         - ./.env

   # bonus:
      # profiles: [bonus]     #used to launch only if specified with docker compose --profile bonus up


networks:
   inception:
      driver: bridge